services:
  ufit.presentation:
    image: ${DOCKER_REGISTRY-}ufitpresentation
    build:
      context: .
      dockerfile: UFit.Presentation/Dockerfile
    depends_on: 
      - ufit.database

  ufit.database:
   image: postgres
   container_name: UFit.Database
   environment:
    - POSTGRES_DB=ufit-db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
   ports:
    - "5432:5432"
   volumes:
    - ./.containers/data:/var/lib/postgresql/data
  
   
