services:
  ufit.presentation:
    image: ${DOCKER_REGISTRY-}ufitpresentation
    build:
      context: .
      dockerfile: UFit.Presentation/Dockerfile

  ufit.database:
   image: postgres
   container_name: UFit.Database
   environment:
    - POSTGRES_DB=ufit-db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
   ports:
    - "5432:5432"
   
